export const PULLS_REQUEST = 'PULLS_REQUEST';
export const PULLS_SUCCESS = 'PULLS_SUCCESS';
export const PULLS_FAILURE = 'PULLS_FAILURE';

export const GET_REPOSITORIES = 'get_repositories';

export const REPOS_GET_REQUEST = 'REPOS_GET_REQUEST'
export const REPOS_GET_SUCCESS = 'REPOS_GET_SUCCESS' 
export const REPOS_GET_FAIL = 'REPOS_GET_FAIL'

export const REPO_ACTIVATED = 'REPO_ACTIVATED'
export const SELECTED_PULLREQUESTS = 'SELECTED_PULLREQUESTS'

export const COLOR_SELECTED = 'COLOR_SELECTED'


export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';