export const PULLS_REQUEST = 'PULLS_REQUEST'
export const PULLS_SUCCESS = 'PULLS_SUCCESS'
export const PULLS_FAILURE = 'PULLS_FAILURE'

export const GET_REPOSITORIES = 'get_repositories'

export const TOGGLE_WEBHOOK_REQUEST = 'TOGGLE_WEBHOOK_REQUEST'
export const TOGGLE_WEBHOOK_SUCCESS = 'TOGGLE_WEBHOOK_SUCCESS'
export const TOGGLE_WEBHOOK_FAILURE = 'TOGGLE_WEBHOOK_FAILURE'