export const REPOS_GET = 'REPOS_GET'
export const PULLS_GET = 'PULLS_GET';

export const REPO_ACTIVATED = 'REPO_ACTIVATED'
export const SELECTED_PULLREQUESTS = 'SELECTED_PULLREQUESTS'

export const COLOR_SELECTED = 'COLOR_SELECTED'

export const SOCKETS_PULLS_SET = 'PULLS_SET'

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';
